spring:
  datasource:
    url: jdbc:mysql://localhost/tfgprojecttest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
    username: tfg
    password: tfg
    max-active: 1
    max-idle: 1
